//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int articleID { get; set; }
        public string article_name { get; set; }
        public string article_sub_heading { get; set; }
        public Nullable<bool> isfeatured { get; set; }
        public Nullable<bool> isBreaking { get; set; }
        public string category { get; set; }
        public string content { get; set; }
        public Nullable<int> authorID { get; set; }
        public string imageUrl { get; set; }
    
        public virtual author author { get; set; }
    }
}
